title: Vidhi Singhal | Industrial Automation & Vision Engineer.
description: Engineering Student • C++ Developer • Computer Vision • Industrial Systems
author:
  name: "Vidhi Singhal"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/isvidhi"
theme: jekyll-theme-hacker
# remote_theme: pages-themes/hacker@main
# plugins:
#   - jekyll-remote-theme

# Optional: Add social links if your chosen theme supports them natively
linkedin: isvidhi
email: hcpsvidhi25@gmail.com
